apiVersion: v2
name: stateless-dns
description: A Helm chart to integrate external-dns and powerdns so they work stateless

maintainers:
- name: kang-makes
  url: https://github.com/kang-makes
- name: roobre
  url: https://github.com/roobre

type: application

# This version is ignored. The publish-chart workflow sets this to the tag being released using `helm package`.
# Please refer to git tags or GitHub releases to check the version of this chart.
version: 0.0.0
