{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stateless-dns.fullname" . }}
rules:
{{- $hasNode                := has "node"                 .Values.externalDNS.sources }}
{{- $hasPod                 := has "pod"                  .Values.externalDNS.sources }}
{{- $hasService             := has "service"              .Values.externalDNS.sources }}
{{- $hasContourHTTPProxy    := has "contour-httpproxy"    .Values.externalDNS.sources }}
{{- $hasGlooProxy           := has "gloo-proxy"           .Values.externalDNS.sources }}
{{- $hasOpenshiftRoute      := has "openshift-route"      .Values.externalDNS.sources }}
{{- $hasSkipperRoutegroup   := has "skipper-routegroup"   .Values.externalDNS.sources }}
{{- $hasIstioGateway        := has "istio-gateway"        .Values.externalDNS.sources }}
{{- $hasIstioVirtualservice := has "istio-virtualservice" .Values.externalDNS.sources }}
{{- $hasIngress             := has "ingress"              .Values.externalDNS.sources }}
{{- $hasAmbassadorHost      := has "ambassador-host"      .Values.externalDNS.sources }}
{{- $hasContourIngressroute := has "contour-ingressroute" .Values.externalDNS.sources }}
{{- $hasCRD                 := has "crd"                  .Values.externalDNS.sources }}
{{- $hasGatewayHTTPRoute    := has "gateway-httproute"    .Values.externalDNS.sources }}
{{- $hasGatewayGRPCRoute    := has "gateway-grpcroute"    .Values.externalDNS.sources }}
{{- $hasGatewayTLSRoute     := has "gateway-tlsroute"     .Values.externalDNS.sources }}
{{- $hasGatewayTCPRoute     := has "gateway-tcproute"     .Values.externalDNS.sources }}
{{- $hasGatewayUDPRoute     := has "gateway-udproute"     .Values.externalDNS.sources }}
{{- $hasKongTCPIngress      := has "kong-tcpingress"      .Values.externalDNS.sources }}
{{- $hasTraefikProxy        := has "traefik-proxy"        .Values.externalDNS.sources }}
{{- $hasF5VirtualServer     := has "f5-virtualserver"     .Values.externalDNS.sources }}
{{- $hasF5TransportServer   := has "f5-transportserver"   .Values.externalDNS.sources }}


{{- if or $hasNode $hasPod $hasService $hasContourHTTPProxy $hasGlooProxy $hasOpenshiftRoute $hasSkipperRoutegroup }}
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","watch"]
{{- end }}
{{- if or $hasPod $hasService $hasContourHTTPProxy $hasGlooProxy $hasOpenshiftRoute $hasSkipperRoutegroup }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if or $hasService $hasContourHTTPProxy $hasGlooProxy $hasIstioGateway $hasIstioVirtualservice $hasOpenshiftRoute $hasSkipperRoutegroup }}
  - apiGroups: [""]
    resources: ["services","endpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if or $hasIngress $hasContourHTTPProxy $hasOpenshiftRoute $hasSkipperRoutegroup }}
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if or $hasIstioGateway $hasIstioVirtualservice }}
  - apiGroups: ["networking.istio.io"]
    resources: ["gateways"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasIstioVirtualservice }}
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasAmbassadorHost }}
  - apiGroups: ["getambassador.io"]
    resources: ["hosts","ingresses"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasContourHTTPProxy }}
  - apiGroups: ["projectcontour.io"]
    resources: ["httpproxies"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasContourIngressroute }}
  - apiGroups: ["contour.heptio.com"]
    resources: ["ingressroutes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasCRD }}
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints/status"]
    verbs: ["*"]
{{- end }}
{{- if or $hasGatewayHTTPRoute $hasGatewayGRPCRoute $hasGatewayTLSRoute $hasGatewayTCPRoute }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways"]
    verbs: ["get","watch","list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasGatewayHTTPRoute }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasGatewayGRPCRoute }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["grpcroutes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasGatewayTLSRoute }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["tlsroutes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasGatewayTCPRoute }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["tcproutes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasGatewayUDPRoute }}
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["udproutes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasGlooProxy }}
  - apiGroups: ["gloo.solo.io","gateway.solo.io"]
    resources: ["proxies","virtualservices"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasKongTCPIngress }}
  - apiGroups: ["configuration.konghq.com"]
    resources: ["tcpingresses"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasOpenshiftRoute }}
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasTraefikProxy }}
  - apiGroups: ["traefik.containo.us", "traefik.io"]
    resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if $hasSkipperRoutegroup }}
  - apiGroups: ["zalando.org"]
    resources: ["routegroups"]
    verbs: ["get","watch","list"]
  - apiGroups: ["zalando.org"]
    resources: ["routegroups/status"]
    verbs: ["patch","update"]
{{- end }}
{{- if or $hasF5VirtualServer $hasF5TransportServer }}
  - apiGroups: ["cis.f5.com"]
    resources: ["virtualservers", "transportservers"]
    verbs: ["get","watch","list"]
{{- end }}

{{- end }}
