apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "pdns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stateless-dns.labels" . | nindent 4 }}
    {{- include "pdns.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pdns.selectorLabels" . | nindent 6 }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/apikey-secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/zones: {{ include (print $.Template.BasePath "/zones-configmap.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/config-configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "stateless-dns.labels" . | nindent 8 }}
        {{- include "pdns.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stateless-dns.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      containers:
        - name: pdns
          image: "{{ .Values.pdns.image.registry }}/{{ .Values.pdns.image.repository }}:{{ .Values.pdns.image.tag }}"
          imagePullPolicy: {{ .Values.pdns.pullPolicy }}
          {{- with .Values.pdns.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - /bin/bash
            - /entrypoint/script
            - /usr/local/sbin/pdns_server
          args:
            {{- if .Values.service.api.enabled }}
            - --api-key=$(POWERDNS_API_KEY)
            {{- end }}
            {{- range $arg := .Values.pdns.extraArgs }}
            - {{ $arg }}
            {{- end }}
          {{- if or .Values.service.api.enabled .Values.service.dnsUdp.enabled .Values.service.dnsTcp.enabled }}
          ports:
            {{- if .Values.service.dnsTcp.enabled }}
            - name: dns-tcp
              protocol: TCP
              containerPort: {{ .Values.service.dnsTcp.port }}
            {{- end }}
            {{- if .Values.service.dnsUdp.enabled }}
            - name: dns-udp
              protocol: UDP
              containerPort: {{ .Values.service.dnsUdp.port }}
            {{- end }}
            {{- if .Values.service.api.enabled }}
            - name: http
              protocol: TCP
              containerPort: {{ .Values.service.api.port }}
            {{- end }}
          {{- end }}
          env:
            - name: "POWERDNS_API_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ include "pdns.secret.name" . }}
                  key: {{ include "pdns.secret.key" . }}
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /usr/local/etc/pdns.conf
              name: config
              subPath: pdns.conf
            - mountPath: /zones
              name: zones
          resources:
            {{- toYaml .Values.pdns.resources | nindent 12 }}
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "stateless-dns.fullname" . }}-config
        - name: zones
          configMap:
            name: {{ include "stateless-dns.fullname" . }}-zones
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
