{{- if .Values.pdns.apiKeySecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdns.secret.name" . }}
type: Opaque
{{- if .Values.pdns.apiKeySecret.valueBase64 }}
data:
  {{ include "pdns.secret.key" . }}: {{ .Values.pdns.apiKeySecret.valueBase64 }}
{{- else }}
stringData:
  {{ include "pdns.secret.key" . }}: {{ .Values.pdns.apiKeySecret.valuePlain }}
{{- end }}
{{- end }}
