---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stateless-dns.fullname" . }}-zones
  labels:
    {{- include "stateless-dns.labels" . | nindent 4 }}
data:
  {{- with .Values.zones }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
