---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stateless-dns.fullname.withSuffix" ( dict "context" . "suffix" "zones" ) }}
  labels:
    {{- include "stateless-dns.labels" . | nindent 4 }}
data:
  {{- with .Values.zones }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
