{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stateless-dns.fullname" . }}
rules:
{{- if or (has "node" .Values.externalDNS.sources) (has "pod" .Values.externalDNS.sources) (has "service" .Values.externalDNS.sources) (has "contour-httpproxy" .Values.externalDNS.sources) (has "gloo-proxy" .Values.externalDNS.sources) (has "openshift-route" .Values.externalDNS.sources) (has "skipper-routegroup" .Values.externalDNS.sources) }}
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list","watch"]
{{- end }}
{{- if or (has "pod" .Values.externalDNS.sources) (has "service" .Values.externalDNS.sources) (has "contour-httpproxy" .Values.externalDNS.sources) (has "gloo-proxy" .Values.externalDNS.sources) (has "openshift-route" .Values.externalDNS.sources) (has "skipper-routegroup" .Values.externalDNS.sources) }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if or (has "service" .Values.externalDNS.sources) (has "contour-httpproxy" .Values.externalDNS.sources) (has "gloo-proxy" .Values.externalDNS.sources) (has "istio-gateway" .Values.externalDNS.sources) (has "istio-virtualservice" .Values.externalDNS.sources) (has "openshift-route" .Values.externalDNS.sources) (has "skipper-routegroup" .Values.externalDNS.sources) }}
  - apiGroups: [""]
    resources: ["services","endpoints"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if or (has "ingress" .Values.externalDNS.sources) (has "contour-httpproxy" .Values.externalDNS.sources) (has "openshift-route" .Values.externalDNS.sources) (has "skipper-routegroup" .Values.externalDNS.sources) }}
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if or (has "istio-gateway" .Values.externalDNS.sources) (has "istio-virtualservice" .Values.externalDNS.sources) }}
  - apiGroups: ["networking.istio.io"]
    resources: ["gateways"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "istio-virtualservice" .Values.externalDNS.sources }}
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "ambassador-host" .Values.externalDNS.sources }}
  - apiGroups: ["getambassador.io"]
    resources: ["hosts","ingresses"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "contour-httpproxy" .Values.externalDNS.sources }}
  - apiGroups: ["projectcontour.io"]
    resources: ["httpproxies"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "contour-ingressroute" .Values.externalDNS.sources }}
  - apiGroups: ["contour.heptio.com"]
    resources: ["ingressroutes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "crd" .Values.externalDNS.sources }}
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints"]
    verbs: ["get","watch","list"]
  - apiGroups: ["externaldns.k8s.io"]
    resources: ["dnsendpoints/status"]
    verbs: ["*"]
{{- end }}
{{- if has "gloo-proxy" .Values.externalDNS.sources }}
  - apiGroups: ["gloo.solo.io","gateway.solo.io"]
    resources: ["proxies","virtualservices"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "kong-tcpingress" .Values.externalDNS.sources }}
  - apiGroups: ["configuration.konghq.com"]
    resources: ["tcpingresses"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "openshift-route" .Values.externalDNS.sources }}
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["get","watch","list"]
{{- end }}
{{- if has "skipper-routegroup" .Values.externalDNS.sources }}
  - apiGroups: ["zalando.org"]
    resources: ["routegroups"]
    verbs: ["get","watch","list"]
  - apiGroups: ["zalando.org"]
    resources: ["routegroups/status"]
    verbs: ["patch","update"]
{{- end }}
{{- with .Values.rbac.additionalPermissions }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
