name: Build PDNS image

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'charts/dns/values.yaml'

concurrency: 
  group: image-builder
  cancel-in-progress: true

env:
  DOCKER_PLATFORMS: "linux/amd64,linux/arm64,linux/arm"

jobs:
  get-latest-version:
    runs-on: ubuntu-latest
    outputs:
      tag:   ${{ steps.test-upgrade.outputs.tag }}
      match: ${{ steps.test-upgrade.outputs.match }}
    steps:
    - uses: actions/checkout@v2
    - id: test-upgrade
      run: |
        docker run quay.io/skopeo/stable:latest inspect \
          docker://ghcr.io/txqueuelen/pdns-stateless > inspection.json

        echo Found tags in this repository:
        jq -r '.RepoTags[]' inspection.json

        TAG=$(yq .pdns.tag charts/dns/values.yaml)
        MINOR=$(cut -d. -f1-2 <<<"${TAG}")
        MAJOR=$(cut -d. -f1   <<<"${TAG}")

        echo tag=$TAG     >> $GITHUB_OUTPUT
        echo minor=$MINOR >> $GITHUB_OUTPUT
        echo major=$MAJOR >> $GITHUB_OUTPUT

        MATCH_LINES=$(jq -r '.RepoTags[]' inspection.json | grep "$TAG" | wc -l)
        if [ $MATCH_LINES -eq 0 ]; then
          echo match=false  >> $GITHUB_OUTPUT
        else
          echo match=true >> $GITHUB_OUTPUT
        fi

  build-image:
    runs-on: ubuntu-latest
    needs: get-latest-version
    if: ${{ needs.get-latest-version.outputs.match == 'false' }}
    steps:
    - name: Checkout PowerDNS
      uses: actions/checkout@v3
      with:
        repository: PowerDNS/pdns
        path: upstream
        ref: auth-${{ needs.get-latest-version.outputs.tag }}
    - name: Checkout this repository
      uses: actions/checkout@v3
      with:
        path: local
    
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2

    - name: Build pdns image
      run: |
        docker buildx build --platform=$DOCKER_PLATFORMS \
          -t temporary-pdns:${{ needs.get-latest-version.outputs.tag }} \
          ./upstream

    - name: Build modified image
      run: |
        docker buildx build --platform=$DOCKER_PLATFORMS \
          --build-arg TAG=${{ needs.get-latest-version.outputs.tag }} \
          -t ghcr.io/${{ github.repository }}:${{ needs.get-latest-version.outputs.tag }} \
          -t ghcr.io/${{ github.repository }}:${{ needs.get-latest-version.outputs.minor }} \
          -t ghcr.io/${{ github.repository }}:${{ needs.get-latest-version.outputs.major }} \
          -t ghcr.io/${{ github.repository }}:latest \
          ./local

    - name: Push image in case this is merged to main
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        docker buildx build --push --platform=$DOCKER_PLATFORMS \
          --build-arg TAG=${{ needs.get-latest-version.outputs.tag }} \
          -t ghcr.io/${{ github.repository }}:${{ needs.get-latest-version.outputs.tag }} \
          -t ghcr.io/${{ github.repository }}:${{ needs.get-latest-version.outputs.minor }} \
          -t ghcr.io/${{ github.repository }}:${{ needs.get-latest-version.outputs.major }} \
          -t ghcr.io/${{ github.repository }}:latest \
          ./local
