name: Release charts

on:
  push:
    branches:
      - main

# Prevent two release workflows from running concurrently.
concurrency: 
  group: chart-releaser
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # TODO: Create here the README.md.
      # If the readme is created at this point at push time the workflow will be aborted and will start again.
      # https://github.com/norwoodj/helm-docs

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
