name: Release tagged image

on:
  release:
    types: [ released ]

jobs:
  release:
    name: Push image to latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull prerelease and pull as latest
        run: |
          docker pull ghcr.io/${{ github.repository }}:"$GITHUB_REF_NAME"

          docker tag \
            ghcr.io/${{ github.repository }}:"$GITHUB_REF_NAME" \
            ghcr.io/${{ github.repository }}:latest

          docker push ghcr.io/${{ github.repository }}:latest
